In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [12]:
#Logistic Regression
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\Dell\OneDrive\Documents\envs\py36\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9592592592592593

In [11]:
#svm
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.987037037037037

In [13]:
#random first
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9648148148148148

In [14]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [23]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [28]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [25]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [31]:
scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    
    scores_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [32]:
scores_l

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [33]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [34]:
scores_rf

[0.9348914858096828, 0.9499165275459098, 0.9398998330550918]

In [35]:
#cross val score function
from sklearn.model_selection import cross_val_score

In [38]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [39]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [40]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)

array([0.92320534, 0.95325543, 0.91986644])

In [41]:
#parameter tuning using k-fold
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8814773432650528

In [42]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores1)

0.9343296089385473

In [43]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores1)

0.9415704531346989

In [46]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=60),digits.data, digits.target, cv=10)
np.average(scores1)

0.9493482309124767

In [47]:
from sklearn.datasets import load_iris
iris=load_iris()

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [53]:
l_scores=cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3)
l_scores

C:\Users\Dell\OneDrive\Documents\envs\py36\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.98, 0.96, 0.98])

In [54]:
np.average(l_scores)

0.9733333333333333

In [57]:
from sklearn.tree import DecisionTreeClassifier

In [59]:
d_scores=cross_val_score(DecisionTreeClassifier(),iris.data, iris.target,cv=3)
d_scores

array([0.98, 0.94, 0.98])

In [60]:
np.average(d_scores)

0.9666666666666667

In [61]:
s_scores=cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv=3)
s_scores

array([0.98, 0.98, 0.96])

In [62]:
np.average(s_scores)

0.9733333333333333

In [64]:
r_scores=cross_val_score(RandomForestClassifier(n_estimators=40),iris.data, iris.target, cv=3)
r_scores

array([0.98, 0.92, 0.94])

In [65]:
np.average(r_scores)

0.9466666666666667