In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model 

In [2]:
df=pd.read_csv(r"C:\Users\Dell\Desktop\DBT\homepricesm.csv")

In [4]:
df.head(10)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
import math
median_bedrooms = math.floor(df.bedrooms.median())

In [7]:
median_bedrooms

4

In [8]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [10]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
reg.intercept_

221323.00186540408

In [12]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [13]:
112.06244194*3000+23388.88007794*3+-3231.71790863*40+221323.00186540408

498408.2515740241

In [14]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [28]:
df2 = pd.read_csv(r"C:\Users\Dell\Desktop\DBT\hiring.csv",delimiter=r'\t')

C:\Users\Dell\OneDrive\Documents\envs\py36\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [30]:
df2.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          8                    9.0                       50000        NaN
1          8                    6.0                       45000        NaN
2       five                    6.0                           7    60000.0
3        two                   10.0                          10    65000.0
4      seven                    9.0                           6    70000.0

In [31]:
import math
median_salary = math.floor(df2['salary($)'].median())

In [32]:
median_salary

67500

In [34]:
df2['salary($)']=df2['salary($)'].fillna(median_salary)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          8                    9.0                       50000    67500.0
1          8                    6.0                       45000    67500.0
2       five                    6.0                           7    60000.0
3        two                   10.0                          10    65000.0
4      seven                    9.0                           6    70000.0
5      three                    7.0                          10    62000.0
6        ten                    NaN                           7    72000.0
7     eleven                    7.0                           8    80000.0

In [39]:
median_test_score = math.floor(df2['test_score(out of 10)'].median())
median_test_score

7

In [40]:
df2['test_score(out of 10)'] = df2['test_score(out of 10)'].fillna(median_test_score)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          8                    9.0                       50000    67500.0
1          8                    6.0                       45000    67500.0
2       five                    6.0                           7    60000.0
3        two                   10.0                          10    65000.0
4      seven                    9.0                           6    70000.0
5      three                    7.0                          10    62000.0
6        ten                    7.0                           7    72000.0
7     eleven                    7.0                           8    80000.0

In [46]:
df2.replace({'five':5,'two':2,'seven':7,'three':3,'ten':10,'eleven':11},inplace=True)

In [47]:
df2.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          8                    9.0                       50000    67500.0
1          8                    6.0                       45000    67500.0
2          5                    6.0                           7    60000.0
3          2                   10.0                          10    65000.0
4          7                    9.0                           6    70000.0

In [48]:
reg = linear_model.LinearRegression()
reg.fit(df2[['experience','test_score(out of 10)','interview_score(out of 10)']],df2['salary($)'])

LinearRegression()

In [49]:
reg.coef_

array([ 1.94595825e+03,  1.45315263e+03, -8.01494709e-02])

In [50]:
reg.intercept_

44736.74892225393

In [51]:
reg.predict([[2,9,6]])

array([61706.55816118])

In [53]:
reg.predict([[12,10,10]])

array([82618.97264915])